name: 'Bump Version'
description: 'Updates version in all .csproj files and commits the changes'
inputs:
  version:
    description: 'Version to set in .csproj files'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Update version in .csproj files
      shell: bash
      run: |
        # Find all .csproj files with <Version> tags and update them
        find . -name "*.csproj" -type f | while read file; do
          if grep -q "<Version>" "$file"; then
            sed -i.bak "s|<Version>.*</Version>|<Version>${{ inputs.version }}</Version>|g" "$file"
            rm "${file}.bak"
            echo "Updated version in $file"
          fi
        done

    - name: Commit version bump
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add "*.csproj"
        if git diff --cached --quiet; then
          echo "No version changes to commit"
        else
          git commit -m "chore: bump version to ${{ inputs.version }}"
          git push origin HEAD
        fi
