name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0 or v1.0.0)'
        required: true
        type: string

jobs:
  create-tag:
    name: Create Tag
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      version: ${{ steps.normalize_version.outputs.version }}
      tag: ${{ steps.normalize_version.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Normalize version
        id: normalize_version
        uses: ./.github/actions/normalize-version
        with:
          version: ${{ github.event.inputs.version }}

      - name: Bump version in .csproj files
        uses: ./.github/actions/bump-version
        with:
          version: ${{ steps.normalize_version.outputs.version }}

      - name: Create and push tag
        uses: ./.github/actions/create-tag
        with:
          tag: ${{ steps.normalize_version.outputs.tag }}

  publish-nuget:
    name: Publish NuGet Packages
    needs: create-tag
    uses: ./.github/workflows/publish_nuget.yml
    with:
      version: ${{ needs.create-tag.outputs.version }}
    permissions:
      packages: write
      contents: read

  create-release:
    name: Create GitHub Release
    needs: [create-tag, publish-nuget]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.create-tag.outputs.tag }}
          name: Release ${{ needs.create-tag.outputs.tag }}
          generateReleaseNotes: true
          body: |
            NuGet packages published to GitHub Packages.

            ### Installation
            ```bash
            dotnet add package DataPlane.Sdk.Core --version ${{ needs.create-tag.outputs.version }}
            dotnet add package DataPlane.Sdk.Api --version ${{ needs.create-tag.outputs.version }}
            ```
          draft: false
          prerelease: false
